'use client'

import { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import type { PickList, PickListBin } from '@/types/database'
import { ClipboardList, CheckCircle2, Clock, ChevronRight, Package } from 'lucide-react'

export default function PickListsPage() {
  const router = useRouter()
  const supabase = createClient()
  const [active, setActive] = useState<PickList[]>([])
  const [completed, setCompleted] = useState<PickList[]>([])
  const [loading, setLoading] = useState(true)
  const [tab, setTab] = useState<'active' | 'completed'>('active')

  const load = useCallback(async () => {
    const { data: lists } = await supabase
      .from('pick_lists')
      .select('*')
      .order('generated_at', { ascending: false })

    if (lists) {
      setActive((lists as PickList[]).filter(l => l.status !== 'complete'))
      setCompleted((lists as PickList[]).filter(l => l.status === 'complete'))
    }
    setLoading(false)
  }, [supabase])

  useEffect(() => { load() }, [load])

  function countTotes(pl: PickList) {
    const bins = pl.bins as PickListBin[]
    return bins.reduce((sum, b) => sum + b.totes.length, 0)
  }

  function countPicked(pl: PickList) {
    const bins = pl.bins as PickListBin[]
    return bins.reduce((sum, b) => sum + b.totes.filter(t => t.status === 'picked').length, 0)
  }

  if (loading) {
    return (
      <div className="px-5 pt-6 space-y-4">
        {[1, 2].map(i => <div key={i} className="h-24 bg-gray-200 rounded-2xl animate-pulse" />)}
      </div>
    )
  }

  return (
    <div className="px-5 pt-6 pb-6 space-y-5">
      <h1 className="font-black text-2xl text-brand-navy">Pick Lists</h1>
      <p className="text-sm text-gray-500 -mt-3">Pick lists are generated by admin. Tap to start picking.</p>

      {/* Tab switcher */}
      <div className="flex bg-gray-100 rounded-2xl p-1">
        {(['active', 'completed'] as const).map(t => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`flex-1 py-2.5 rounded-xl text-sm font-bold transition-all ${
              tab === t ? 'bg-white text-brand-navy shadow-sm' : 'text-gray-500'
            }`}
          >
            {t === 'active' ? `Active (${active.length})` : `Done Today (${completed.length})`}
          </button>
        ))}
      </div>

      {/* Active lists */}
      {tab === 'active' && (
        <>
          {active.length === 0 ? (
            <div className="text-center py-12">
              <ClipboardList className="w-12 h-12 text-gray-300 mx-auto mb-3" />
              <p className="font-bold text-gray-400 text-lg">No Active Pick Lists</p>
              <p className="text-gray-400 text-sm mt-1">Admin will generate pick lists when totes are needed.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {active.map(pl => {
                const total = countTotes(pl)
                const picked = countPicked(pl)
                const pct = total > 0 ? Math.round((picked / total) * 100) : 0
                return (
                  <button
                    key={pl.id}
                    onClick={() => router.push(`/warehouse/pick-lists/${pl.id}`)}
                    className="card w-full text-left hover:shadow-md active:scale-[0.98] transition-all"
                  >
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-brand-blue/10 flex items-center justify-center flex-shrink-0">
                        <ClipboardList className="w-5 h-5 text-brand-blue" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="font-bold text-brand-navy text-sm">{pl.id}</span>
                          <span className={`status-pill text-xs ${
                            pl.status === 'in_progress' ? 'bg-yellow-100 text-yellow-700' : 'bg-blue-100 text-blue-700'
                          }`}>
                            {pl.status === 'in_progress' ? 'In Progress' : 'Ready'}
                          </span>
                        </div>
                        <p className="text-xs text-gray-500 mt-0.5">
                          {(pl.bins as PickListBin[]).length} bins · {total} totes
                        </p>
                      </div>
                      <ChevronRight className="w-4 h-4 text-gray-300 flex-shrink-0" />
                    </div>
                    {/* Progress bar */}
                    <div className="mt-3">
                      <div className="flex justify-between text-xs text-gray-500 mb-1">
                        <span>{picked} / {total} picked</span>
                        <span>{pct}%</span>
                      </div>
                      <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-brand-blue rounded-full transition-all"
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                    </div>
                  </button>
                )
              })}
            </div>
          )}
        </>
      )}

      {/* Completed lists */}
      {tab === 'completed' && (
        <>
          {completed.length === 0 ? (
            <div className="text-center py-12">
              <CheckCircle2 className="w-12 h-12 text-gray-300 mx-auto mb-3" />
              <p className="font-bold text-gray-400 text-lg">No Completed Lists Today</p>
            </div>
          ) : (
            <div className="space-y-3">
              {completed.map(pl => {
                const total = countTotes(pl)
                return (
                  <div key={pl.id} className="card opacity-75">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
                        <CheckCircle2 className="w-5 h-5 text-green-600" />
                      </div>
                      <div className="flex-1">
                        <p className="font-bold text-brand-navy text-sm">{pl.id}</p>
                        <p className="text-xs text-gray-500">
                          {total} totes · Completed {pl.completed_at
                            ? new Date(pl.completed_at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
                            : ''}
                        </p>
                      </div>
                      <span className="status-pill bg-green-100 text-green-700 text-xs">Done</span>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </>
      )}
    </div>
  )
}
